# Generated by Django 4.0.5 on 2022-06-05 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Basetable',
            new_name='InfuraInitial',
        ),
    ]
